name: helper
author: Luck, Envel
version: 1.17
description: ${project.description}
main: me.lucko.helper.internal.StandalonePlugin
website: https://github.com/lucko/helper
load: STARTUP
softdepend: [ProtocolLib, Citizens, ViaVersion]